services:
  storage:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  init-minio:
    image: minio/mc:latest
    depends_on:
      storage:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://storage:9000 minioadmin minioadmin;
      /usr/bin/mc admin user add myminio techtalk techtalk;
      /usr/bin/mc admin policy attach myminio readwrite --user=techtalk;
      if /usr/bin/mc ls myminio/techtalk > /dev/null 2>&1; then
        /usr/bin/mc rm -r --force myminio/techtalk;
      fi;
      if ! /usr/bin/mc ls myminio/techtalk > /dev/null 2>&1; then
        /usr/bin/mc mb myminio/techtalk;
      fi;
      exit 0;"
