# fly.toml app configuration file generated for techtalk-jp on 2024-02-27T23:20:07+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'techtalk-jp'
primary_region = 'nrt'

[[vm]]
  size = 'shared-cpu-1x'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "20s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/healthcheck"
