# fly.toml app configuration file generated for techtalk-jp-summer-sound-3160 on 2024-04-07T13:45:33+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'techtalkjp'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/healthcheck'

[[vm]]
  size = 'shared-cpu-1x'
