onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - duckdb
  - esbuild
  - sharp
  - workerd

patchedDependencies:
  decode-named-character-reference@1.1.0: patches/decode-named-character-reference@1.1.0.patch
