// Generated by Wrangler by running `wrangler types`

interface Env {
	SLACK_WEBHOOK: string;
	SENDGRID_API_KEY: string;
	TURSO_URL: string;
	TURSO_AUTH_TOKEN: string;
	IMAGE_ENDPOINT_URL: string;
	ENV: string;
	GOOGLE_GENERATIVE_AI_API_KEY: string;
	R2: R2Bucket;
	MAIL_QUEUE: Queue;
	ASSETS: Fetcher;
}
