#:schema node_modules/wrangler/config-schema.json
name = "techtalkjp"

account_id = "91ff95bcb91fbfa1b1c5c356262b1fe4"
main = "./server.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-03-02"

# https://developers.cloudflare.com/workers/static-assets/binding/
assets = { directory = "./build/client", binding = 'ASSETS'}

[observability]
enabled = true

[[r2_buckets]]
binding = 'R2'
bucket_name = 'techtalk'

[[queues.producers]]
queue = 'techtalk-contact-email'
binding = 'CONTACT_QUEUE'

[[queues.consumers]]
queue = 'techtalk-contact-email'
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3
dead_letter_queue = 'mail-processing-dlq'

[build]
command = "pnpm run build"

[env.development]
name = 'techtalkjp-dev'
vars = { ENV = 'development'}

[env.production]
name = 'techtalkjp'
vars = { ENV = 'production'}