-- Migration number: 0002    2026-03-02T00:00:00.000Z

CREATE TABLE IF NOT EXISTS fts_contents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE VIRTUAL TABLE IF NOT EXISTS fts_index USING fts5(title, body);
