name: build and unit tests
on:
  - push
  - pull_request

jobs:
  test:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 8.6.1
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install
      - name: Run tests
        run: |
          pnpm build
          pnpm test:run
