import { createHash } from 'node:crypto'
import { spawnSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import {
  ML_LABELS,
  predictText,
  textFeatures,
} from '../../workers/workflow/services/text-features.ts'

export const train = (samples, source) => {
  if (!samples.length) throw new Error('No training samples')
  if (
    samples.some(
      (row) =>
        !ML_LABELS.includes(row.label) || typeof row.message !== 'string',
    )
  ) {
    throw new Error(
      'Every sample requires message and a sales/gray/normal label',
    )
  }
  if (ML_LABELS.some((label) => !samples.some((row) => row.label === label))) {
    throw new Error('Training requires all three classes')
  }
  const counts = new Map()
  for (const row of samples) {
    for (const feature of textFeatures(row.message))
      counts.set(feature, (counts.get(feature) ?? 0) + 1)
  }
  const vocabulary = [...counts]
    .filter(([, count]) => count >= 2)
    .sort(([a], [b]) => a.localeCompare(b, 'en'))
    .map(([feature]) => feature)
  const weights = Object.fromEntries(
    vocabulary.map((feature) => [feature, [0, 0, 0]]),
  )
  const bias = [0, 0, 0]
  const vectors = samples.map((row) => {
    const features = [...textFeatures(row.message)].filter((feature) =>
      Object.hasOwn(weights, feature),
    )
    return {
      features,
      scale: 1 / Math.sqrt(features.length || 1),
      target: ML_LABELS.indexOf(row.label),
    }
  })
  // 決定的な全バッチsoftmax回帰。小規模データ用のL2正則化。
  for (let epoch = 0; epoch < 400; epoch++) {
    const gradient = Object.fromEntries(
      vocabulary.map((feature) => [feature, [0, 0, 0]]),
    )
    const biasGradient = [0, 0, 0]
    for (const vector of vectors) {
      const logits = bias.map(
        (value, index) =>
          value +
          vector.features.reduce(
            (total, feature) => total + weights[feature][index] * vector.scale,
            0,
          ),
      )
      const max = Math.max(...logits)
      const exp = logits.map((value) => Math.exp(value - max))
      const sum = exp.reduce((total, value) => total + value, 0)
      for (let index = 0; index < 3; index++) {
        const error = exp[index] / sum - Number(index === vector.target)
        biasGradient[index] += error
        for (const feature of vector.features)
          gradient[feature][index] += error * vector.scale
      }
    }
    for (let index = 0; index < 3; index++) {
      bias[index] -= (0.8 * biasGradient[index]) / samples.length
      for (const feature of vocabulary)
        weights[feature][index] -=
          0.8 *
          (gradient[feature][index] / samples.length +
            0.002 * weights[feature][index])
    }
  }
  const rounded = Object.fromEntries(
    vocabulary.map((feature) => [
      feature,
      weights[feature].map((value) => Number(value.toFixed(7)) || 0),
    ]),
  )
  const digest = createHash('sha256')
    .update(
      JSON.stringify({
        samples,
        source,
        algorithm: 'char234-softmax-v1',
        weights: rounded,
        bias,
      }),
    )
    .digest('hex')
    .slice(0, 12)
  return {
    version: `char234-lr-v1-${digest}`,
    source,
    trainingCount: samples.length,
    trainingIds: source === 'human-labeled' ? samples.map((row) => row.id) : [],
    weights: rounded,
    bias,
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const [
    input = 'scripts/inquiry/bootstrap.json',
    output = 'workers/workflow/services/text-model.ts',
  ] = process.argv.slice(2).filter((arg) => arg !== '--')
  const rows = JSON.parse(readFileSync(input, 'utf8'))
  const synthetic = input === 'scripts/inquiry/bootstrap.json'
  if (
    !synthetic &&
    rows.some((row) => row.source !== 'human' || !Number.isSafeInteger(row.id))
  ) {
    throw new Error(
      'Real training input must have source=human and numeric inquiry ids; do not use LLM predictions as labels',
    )
  }
  const samples = rows.map((row) => ({
    id: row.id,
    message: row.message,
    label: row.label,
  }))
  const model = train(
    samples,
    synthetic ? 'synthetic-bootstrap' : 'human-labeled',
  )
  writeFileSync(
    output,
    `// Generated by pnpm run inquiry:train. Scores are not calibrated accuracy.\nimport type { TextModel } from './text-features'\nexport const textModel: TextModel = ${JSON.stringify(model, null, 2)}\n`,
  )
  const formatting = spawnSync(
    'pnpm',
    ['exec', 'vp', 'fmt', '-c', '.oxfmtrc.json', output],
    { encoding: 'utf8' },
  )
  if (formatting.status !== 0)
    throw new Error('Model generated but formatting failed')
  console.log(
    JSON.stringify({
      version: model.version,
      source: model.source,
      samples: model.trainingCount,
      features: Object.keys(model.weights).length,
      trainingCorrect: samples.filter(
        (row) => predictText(model, row.message).verdict === row.label,
      ).length,
    }),
  )
}
