// Generated by pnpm fonts:build. Keep the upstream license in public/fonts/OFL.txt.
export const fontStyles = `
@font-face {
  font-family: 'LINE Seed JP';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('/fonts/line-seed-jp-400-189673bb3a72.woff2') format('woff2');
}
@font-face {
  font-family: 'LINE Seed JP';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url('/fonts/line-seed-jp-700-23e56be198d9.woff2') format('woff2');
}
@font-face {
  font-family: 'LINE Seed JP';
  font-style: normal;
  font-weight: 800;
  font-display: swap;
  src: url('/fonts/line-seed-jp-800-15ce895e04a3.woff2') format('woff2');
}
`
