# /// script
# requires-python = ">=3.11"
# dependencies = ["fonttools==4.66.1", "brotli==1.2.0"]
# ///
"""Generate LINE Seed JP subsets from site sources: uv run scripts/build-fonts.py."""

import hashlib
import io
import json
from pathlib import Path
from urllib.request import urlopen

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "public/fonts"
REVISION = "874ec71eac706dd23900d1305449abed6767b7df"
UPSTREAM = f"https://raw.githubusercontent.com/google/fonts/{REVISION}/ofl/lineseedjp"
SOURCES = sorted(
    path for path in (ROOT / "app").rglob("*")
    if path.suffix in {".ts", ".tsx", ".json"} and path.name != "fonts.ts"
)
# Include source strings, translations, errors, punctuation and ASCII for input fields.
# Extra characters in comments/code cost little and avoid fragile JSX text extraction.
characters = set(range(0x20, 0x7F))
for path in SOURCES:
    characters.update(ord(char) for char in path.read_text())

OUTPUT.mkdir(parents=True, exist_ok=True)
faces = []
files = {}
for weight, name in [(400, "Regular"), (700, "Bold"), (800, "ExtraBold")]:
    with urlopen(f"{UPSTREAM}/LINESeedJP-{name}.ttf") as response:
        font = TTFont(io.BytesIO(response.read()), recalcTimestamp=False)
    # 800 is used only by the TechTalk wordmark.
    wanted = set(map(ord, "TechTalk")) if weight == 800 else characters
    supported = wanted & set(font.getBestCmap())
    options = subset.Options()
    # Keep normal horizontal shaping. Optional historical, vertical, full-width,
    # and fraction alternates are not enabled by this site's CSS.
    options.layout_features = [
        "ccmp", "locl", "rlig", "liga", "clig", "calt", "kern", "mark", "mkmk",
    ]
    options.name_IDs += [13, 14]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=sorted(supported))
    subsetter.subset(font)
    font.flavor = "woff2"
    buffer = io.BytesIO()
    font.save(buffer)
    data = buffer.getvalue()
    digest = hashlib.sha256(data).hexdigest()
    filename = f"line-seed-jp-{weight}-{digest[:12]}.woff2"
    (OUTPUT / filename).write_bytes(data)
    files[filename] = digest
    faces.append(
        "@font-face {\n"
        "  font-family: 'LINE Seed JP';\n"
        "  font-style: normal;\n"
        f"  font-weight: {weight};\n"
        "  font-display: swap;\n"
        f"  src: url('/fonts/{filename}') format('woff2');\n"
        "}"
    )
    print(f"{weight}: {len(supported)} characters, {len(data):,} bytes")

for old in OUTPUT.glob("line-seed-jp-*.woff2"):
    if old.name not in files:
        old.unlink()
with urlopen(f"{UPSTREAM}/OFL.txt") as response:
    (OUTPUT / "OFL.txt").write_bytes(response.read())
(ROOT / "app/ui/fonts.ts").write_text(
    "// Generated by pnpm fonts:build. Keep the upstream license in public/fonts/OFL.txt.\n"
    "export const fontStyles = `\n" + "\n".join(faces) + "\n`\n"
)
(ROOT / "scripts/fonts-manifest.json").write_text(json.dumps({
    "upstream": UPSTREAM,
    "sources": {str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest()
                for path in SOURCES},
    "fonts": files,
}, indent=2) + "\n")
